---
# handlers file for wiredobjects.ntp

- name: service restart ntp
  service:
    name: "{{ ntp_service_name }}"
    state: restarted
  when: ntp_service_enabled == "yes" and state_ntp_config_file.changed
